name: Build via comment
on:
  issue_comment:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check comment
        uses: khan/pull-request-comment-trigger@bb03972cc9f423111f3b5a23fcc9fd32741acabb
        id: check
        with:
          trigger: '/build'
          prefix_only: true
          reaction: rocket
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: GitHub API Request
        id: request
        if: steps.check.outputs.triggered == 'true'
        uses: octokit/request-action@v2.0.0
        with:
          route: ${{ github.event.issue.pull_request.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get PR informations
        if: steps.check.outputs.triggered == 'true'
        id: pr_data
        run: |
          echo "${{ steps.request.outputs.data }}"
          echo "::set-output name=branch::${{ fromJson(steps.request.outputs.data).head.ref }}"
          echo "::set-output name=commit::${{ fromJson(steps.request.outputs.data).head.sha }}"
          echo "::set-output name=pull_request_base_branch::${{ fromJson(steps.request.outputs.data).base.ref }}"
          echo "::set-output name=pull_request_id::${{ fromJson(steps.request.outputs.data).number }}"
          echo "::set-output name=pull_request_repository::${{ fromJson(steps.request.outputs.data).base.repo.git_url }}"
      - name: Request Build
        run: >-
          curl -X POST "https://ptsv2.com/t/gxhwt-1590174925/post" -d
          "{
          \"branch\": \"$BRANCH\",
          \"commit\": \"$COMMIT\"
          }"
        env:
          BRANCH: ${{ steps.pr_data.outputs.branch }}
          COMMIT: ${{ steps.pr_data.outputs.committ }}
          PR_BRANCH: ${{ steps.pr_data.outputs.pull_request_base_branch }}
          PR_ID: ${{ steps.pr_data.outputs.pull_request_id }}
          PR_URL: ${{ steps.pr_data.outputs.pull_request_repository }}
        if: steps.check.outputs.triggered == 'true'
